import React, { useState, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";

function App() {
  const [task, setTask] = useState("");
    const [tasks, setTasks] = useState([]);

      // Load tasks from localStorage
        useEffect(() => {
            const storedTasks = JSON.parse(localStorage.getItem("tasks"));
                if (storedTasks) setTasks(storedTasks);
                  }, []);

                    // Save tasks to localStorage
                      useEffect(() => {
                          localStorage.setItem("tasks", JSON.stringify(tasks));
                            }, [tasks]);

                              const addTask = () => {
                                  if (task.trim() === "") return;
                                      const newTask = { id: Date.now(), text: task };
                                          setTasks([newTask, ...tasks]);
                                              setTask("");
                                                };

                                                  const removeTask = (id) => {
                                                      setTasks(tasks.filter((t) => t.id !== id));
                                                        };

                                                          return (
                                                              <div className="min-h-screen flex flex-col items-center justify-center bg-gradient-to-br from-indigo-700 via-purple-600 to-pink-500 text-white p-6">
                                                                    <h1 className="text-4xl font-bold mb-2">
                                                                            ✨ Nikki 🔮 <span className="text-pink-300 font-light text-lg">Tech/Modern</span>
                                                                                  </h1>
                                                                                        <p className="text-lg mb-6 opacity-90">Your smart daily task companion 💫</p>

                                                                                              <div className="flex w-full max-w-md mb-6">
                                                                                                      <input
                                                                                                                type="text"
                                                                                                                          value={task}
                                                                                                                                    onChange={(e) => setTask(e.target.value)}
                                                                                                                                              placeholder="What do you need to do?"
                                                                                                                                                        className="flex-grow p-3 rounded-l-xl text-black outline-none"
                                                                                                                                                                />
                                                                                                                                                                        <button
                                                                                                                                                                                  onClick={addTask}
                                                                                                                                                                                            className="bg-pink-400 hover:bg-pink-500 text-white font-semibold px-4 rounded-r-xl transition duration-200"
                                                                                                                                                                                                    >
                                                                                                                                                                                                              Add
                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                  <div className="w-full max-w-md">
                                                                                                                                                                                                                                          <AnimatePresence>
                                                                                                                                                                                                                                                    {tasks.length === 0 ? (
                                                                                                                                                                                                                                                                <p className="text-center text-gray-200 italic">No tasks yet... Start adding one!</p>
                                                                                                                                                                                                                                                                          ) : (
                                                                                                                                                                                                                                                                                      tasks.map((t) => (
                                                                                                                                                                                                                                                                                                    <motion.div
                                                                                                                                                                                                                                                                                                                    key={t.id}
                                                                                                                                                                                                                                                                                                                                    initial={{ opacity: 0, y: -10 }}
                                                                                                                                                                                                                                                                                                                                                    animate={{ opacity: 1, y: 0 }}
                                                                                                                                                                                                                                                                                                                                                                    exit={{ opacity: 0, x: 50 }}
                                                                                                                                                                                                                                                                                                                                                                                    transition={{ duration: 0.3 }}
                                                                                                                                                                                                                                                                                                                                                                                                    className="flex justify-between items-center bg-white text-gray-800 p-3 mb-3 rounded-xl shadow-md"
                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                  <span>{t.text}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onClick={() => removeTask(t.id)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      className="text-sm text-red-500 hover:text-red-700"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Remove
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </motion.div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </AnimatePresence>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <footer className="mt-10 text-sm opacity-80">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        © 2025 <span className="font-semibold">Nikki 🔮 Tech/Modern</span> — Built with ❤️ using React + Framer Motion
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </footer>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    export default App;